FROM mysql:5.7

COPY docker-entrypoint-initdb.d/* docker-entrypoint-initdb.d/

CMD ["--innodb-use-native-aio=0"]

ENV MYSQL_DATABASE=pfa
ENV MYSQL_USER=pfadocker
ENV MYSQL_PASSWORD=pfadocker
ENV MYSQL_ROOT_PASSWORD=pfadocker
ENV LANG=C.UTF-8

CMD ["mysqld","--default-authentication-plugin=mysql_native_password"]

